version: "3.9"

networks:
  spc-network:
    driver: bridge

services:
  spc-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "33066:3306"
    networks:
      - spc-network

  spc-api:
    #image: spc-api  # Usar imagem local
    image: fabiocondo/spc-api # Usar imagem do seu Docker Hub
    environment:
      DB_HOST: spc-mysql
    networks:
      - spc-network
    volumes:
      - C:\Users\user\Desktop\SPC-V2\Imagens:/app/imagens # Mapeia o diretório de imagens compartilhado com o contêiner
    depends_on:
      - spc-mysql

  spc-proxy:
    build: ./nginx
    image: spc-proxy
    ports:
      - "80:80"
    networks:
      - spc-network
    depends_on:
      - spc-api


  # Se quiser usar a imagem que seta no docker hub
  # docker pull fabiocondo/spc-api
  # docker-compose up --scale spc-api=3

  # Passo 1: Build da aplicacao  (3 comando que contem -Pdocker)
  # ./mvnw clean package
  # ./mvnw clean package -DskipTests
  # ./mvnw clean package -DskipTests -Pdocker

  # Remover os containers
  # docker compose down
  # docker compose down --volumes # Elimina junto com os volumes que guardam dados da BD

  # RESUMO DE COMANDOS POR EXECUTAR
  # ./mvnw clean package -DskipTests -Pdocker
  # docker-compose up --scale spc-api=3