version: "3.9"

networks:
  management-app-network:
    driver: bridge

services:

  management-app-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "33066:3306"
    restart: always
    networks:
      - management-app-network

  management-app-redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: always
    networks:
      - management-app-network

  management-app-api:
    image: fabiocondo/management-api
    environment:
      DB_HOST: management-app-mysql
      REDIS_HOST: management-app-redis
      REDIS_PORT: 6379
    depends_on:
      - management-app-mysql
      - management-app-redis
    restart: always
    networks:
      - management-app-network

  management-app-proxy:
    build: ./nginx
    image: management-app-proxy
    ports:
      - "80:80"
    depends_on:
      - management-app-api
    restart: always
    networks:
      - management-app-network


  # Se quiser usar a imagem que seta no docker hub
  # docker pull fabiocondo/management-api
  # docker-compose up --scale management-api=3

  # docker compose up -d --scale management-api=3

  # Passo 1: Build da aplicacao  (3 comando que contem -Pdocker)
  # ./mvnw clean package
  # ./mvnw clean package -DskipTests
  # ./mvnw clean package -DskipTests -Pdocker

  # Remover os containers
  # docker compose down
  # docker compose down --volumes # Elimina junto com os volumes que guardam dados da BD

  # RESUMO DE COMANDOS POR EXECUTAR
  # ./mvnw clean package -DskipTests -Pdocker
  # docker-compose up --scale management-api=3

  # FORCAR O COMMIT PARA DISPARAR O CI/CD QUANDO FALHAR COM COMMIT
  # git commit --allow-empty -m "chore: retry CI"
  # git push