spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}/e-learning?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Africa/Harare # Docker compose
    username: root
    password: root

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}