server {
    client_max_body_size 100M;  # Única linha que resolve o erro ERR_FAILED 413 (Content Too Large) ao fazer upload de ficheiros em producao

    location / {
        proxy_pass http://management-platform-api:8080;
    }
}