name: CI/CD Pipeline

on:
  push:
    branches: [ '**' ]  # Ajuste temporário para testar em todas as branches
  pull_request:
    branches: [ '**' ]  # Ajuste temporário para testar em todas as branches

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '8'
          cache: maven

      - name: Build with Maven
        run: mvn clean install -Dmaven.test.skip=true

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: fabiocondo/management-api
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
